### ISSUE TITLE
Follow redirection lead to SSRF vulnerability

### ISSUE THREAD

**Issue by AbdurrahmanA** [ospfranco/link-preview-js#105]
Hello everyone
I work as a security researcher in a company, A few days ago this is our developers started to use this library 
For this reason, I did a security research on this library. As a result of the investigation, I have identified an SSRF vulnerability that may be a high priority for us and a critical priority for some users. You used a regex to validate the urls in the Library, that's fine regex works fine as far as I can see but `Follow redirect` by default makes this regex pointless because the attacker can very simply redirect to the internal network with a valid domain and since the library will follow this redirection, it can send requests to endpoints in the local network. `Follow redirect` by default must also be false If you update this way, the library will be more secure.

**To Reproduce**
1.  Create a ngrok session which point your server
2.  Create a script(php, java, node, etc) which redirect to any local endpoint you want to trigger
3. Make library request valid ngrok url (eg `https://9a64-159-146-10-46.ngrok.io/redirect.php`)
4. See the local endpoint is triggered

**Screenshots**
![image](https://user-images.githubusercontent.com/50546655/152685507-bc7bc313-360d-4d0f-a717-165a54c278b4.png)
php script would be like this

![image](https://user-images.githubusercontent.com/50546655/152685392-bd3869d5-58fd-4f1b-bca3-86675eb3c2a3.png)

Response

![image](https://user-images.githubusercontent.com/50546655/152685428-81c54a21-acb2-4a37-a95d-98af58943c22.png)

All tests were done in the latest version of the library

**Comment by ospfranco** [comment]
Ah, this is indeed troublesome, I will gladly fix it ASAP, but I'm short on time atm, if you could create a PR, I will gladly merge it
