### ISSUE TITLE
Non ESM example with Node? 

### ISSUE THREAD

**Issue by webb24h** [ospfranco/link-preview-js#108]
How to use this library with require and not import? I'm using Node with all non esm. I cannot change that for now. I have to use the require structure. Any example on how to use this with this model? Please find my codes below.

```
const getLinkPreview = require('link-preview-js');

// pass the link directly
getLinkPreview(url).then((data) =>
  console.debug(data)
);
```

**Comment by ospfranco** [comment]
non ESM shouldn't be a problem, why don't play around and try importing it different ways, one of the should work

```js
const LinkPreview = require('link-preview-js')
LinkPreview.getLinkPreview(url).then...
```
