### ISSUE TITLE
Not support sound-cloud url

### ISSUE THREAD

**Issue by BalramY** [ospfranco/link-preview-js#109]
**Describe the bug**
When I try to fetch soundCloud's url details I didn't get title and thumbnail
getting this response -> 
{"contentType": "text/html", "description": undefined, "favicons": ["https://www.gstatic.com/mobilesdk/160503_mobilesdk/logo/1x/firebase_64dp.png"], "images": [], "mediaType": "website", "siteName": undefined, "title": "", "url": "https://soundcloud.app.goo.gl/XT7kAYqnM9s79ebq5", "videos": []}

**To Reproduce**
data = await getLinkPreview('https://soundcloud.app.goo.gl/XT7kAYqnM9s79ebq5', { //sound could music url
        headers: {
          'user-agent':
            'Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1',
        },
        timeout: 2000,
      }).then();
**Expected behavior**
I should return image uri and it's title like with other response
should return something same response like youtube
{
  url: "https://www.youtube.com/watch?v=MejbOFk7H6c",
  title: "OK Go - Needing/Getting - Official Video - YouTube",
  siteName: "YouTube",
  description: "Buy the video on iTunes: https://itunes.apple.com/us/album/needing-getting-bundle-ep/id508124847 See more about the guitars at: http://www.gretschguitars.com...",
  images: ["https://i.ytimg.com/vi/MejbOFk7H6c/maxresdefault.jpg"],
  mediaType: "video.other",
  contentType: "text/html; charset=utf-8",
  videos: [],
  favicons:["https://www.youtube.com/yts/img/favicon_32-vflOogEID.png","https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico"]
}

**Desktop (please complete the following information):**
 - OS: mac os
 - chrome, safari
 - 22

**Smartphone (please complete the following information):**
 IOS Simulator (ios 11, ios15.0)

**Comment by ospfranco** [comment]
nothing I can do about that, this is what the server is returning on your query, you might try to follow redirects and whatnot. read the README
