### ISSUE TITLE
2.1.17 Version Need to Bump

### ISSUE THREAD

**Issue by AbdurrahmanA** [ospfranco/link-preview-js#121]
I think the local cache remained while creating the 2.1.17 version, so the implemented features are not in the source.

![image](https://user-images.githubusercontent.com/50546655/177389249-e3d71369-8832-4ba2-b3e3-e458e642948c.png)

![image](https://user-images.githubusercontent.com/50546655/177389321-be7c0667-0612-4537-b379-e8ef96501e75.png)

![image](https://user-images.githubusercontent.com/50546655/177389368-c39b742f-20e3-456d-a185-f266f2300743.png)

**Comment by ospfranco** [comment]
I did another bump and deleted any local cache I had. 2.1.18 is out. thanks for noticing! let me know if it works

**Comment by AbdurrahmanA** [comment]
Okay now its working thanks 👍

![image](https://user-images.githubusercontent.com/50546655/177481017-e89a1746-09ba-4f51-9c7e-000861bc2168.png)
