### ISSUE TITLE
Incompatible patch versions

### ISSUE THREAD

**Issue by pavlikm** [ospfranco/link-preview-js#123]
**Describe the bug**
version 2.1.17 use in ILinkPreviewOptions attribute followRedirects as boolean, but in 2.1.19 is it declared as `followRedirects?: 'follow' | 'error' | 'manual'; ` wich causing error `Type 'true' is not assignable to type '"follow" | "error" | "manual"'`

**To Reproduce**
1. `await getLinkPreview(url, {timeout: 3000, followRedirects: 'follow'});` on version 2.1.17 works
2. `await getLinkPreview(url, {timeout: 3000, followRedirects: 'follow'});` on version 2.1.19 throws error

**Expected behavior**
Despite this version 2.1.19 is versioned as patch version, it must be backward compatible with older version 2.1.17. Otherwise please publish version 3.0.0

**Additional context**
[semver.](https://semver.org/)

**Comment by ospfranco** [comment]
Fine, I'll publish a new version
