### ISSUE TITLE
In the handleRedirects option, the demo code has a conditional that is missing, causing an error on some redirects.  Just need to add another OR statement ```||  "www." + forwardedURLObj.hostname === urlObj.hostname``` to handle another edge case

### ISSUE THREAD

**Issue by tmoes** [ospfranco/link-preview-js#128]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ospfranco** [comment]
@AbdurrahmanA do you understand the problem here? I don't have time to look into it further

**Comment by tmoes** [comment]
Yes I do. I was just raising the issue so you are aware that all edge cases are not handled when comparing urlObj and forwardedURLObj in the handleRedirects option for getLinkPreview()

**Comment by ospfranco** [comment]
I didn't mean you, I meant @AbdurrahmanA because he added the options and would like for him to give me a hand to fix it

**Comment by AbdurrahmanA** [comment]
@tmoes it's just for example, you can specify which edge cases you want to handle by creating your own handler function.

**Comment by ospfranco** [comment]
please make the example as fool-proof as possible @AbdurrahmanA, most people just copy and paste
