### ISSUE TITLE
replace url module with new URL

### ISSUE THREAD

**Issue by rogueturnip** [ospfranco/link-preview-js#137]
Just wanted to suggest that you can remove the old url module with the following
src = new URL(src, rootUrl).toString();

**Comment by ospfranco** [comment]
Since this library also works with React-Native cordova runtimes and also depending on the Node version, the URL global might not be present... not sure if it is a good idea to drop it.

**Comment by ospfranco** [comment]
Yeah, as stated the URL api might not be available on all runtimes. There is no need to change the implementation if it is working properly for now. Closing this.
