### ISSUE TITLE
How to fake location?

### ISSUE THREAD

**Issue by uzaysan** [ospfranco/link-preview-js#46]
I'm using this library and it works great. However I have some problems. My server located in Germany. But my users locate different places. For example I live in Turkey but when I make a request it returns german language. How Can I fake my location?

**Comment by ospfranco** [comment]
thanks for reporting, it is actually an interesting point, if you can feel free to submit a PR, the code is not complex and might be only a matter of adding some header to the outgoing request.

**Comment by uzaysan** [comment]
@ospfranco actually I'm a total newbie. What is pr and how to submit a pr?

**Comment by ospfranco** [comment]
http://oss-watch.ac.uk/resources/pullrequest
