### ISSUE TITLE
Error: link-preview-js could not fetch link information TypeError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by abinayakumaran** [ospfranco/link-preview-js#54]
**Describe the bug**

**To Reproduce**
1. Enter the url https://www.google.com

  `return new Promise((resolve, reject) => {
      getLinkPreview('https://www.google.com').then(res => {
        resolve(res);
      })
        .catch(err => {
          return null;
        })
    });`

**Expected behavior**
A complete details about the link

**Screenshots**
![Screenshot 2020-01-24 at 11 29 29 AM](https://user-images.githubusercontent.com/33099342/73047806-ff768880-3e9c-11ea-8b11-3a239de31d9f.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 6s Plus
 - OS: iOS 13
 - React-native application
 "react-native": "^0.60.5",
 "link-preview-js": "^2.0.1",

**Comment by ospfranco** [comment]
Google has some error in their HTML, try it with a different url, it will work
