### ISSUE TITLE
How to add a timeout to requests?

### ISSUE THREAD

**Issue by iMrDJAi** [ospfranco/link-preview-js#55]
I'm trying to deal with links of closed sites like this one: `bac.onec.dz`.
If you try it [here](https://embed-js.glitch.me/apipage) you will not gonna get a response form the server, because the site is closed, so it should be a timeout there.
That's my code (USING EXPRESS.JS):
```js
app.get("/api", async function(request, response) {
  var url = request.query.url;
  if (url) {
    url = decodeURIComponent(url);
    if (!url.match(/^[a-zA-Z]+:\/\//)) url = "http://" + url;
    console.log(url);
    const data = await getLinkPreview(url).catch(err => response.send('URL Error'));
    if (data) response.send(data);
  } else {
    response.send("Query Error");
  }
});
```
And that's the project link: https://glitch.com/edit/#!/embed-js .
So how? and thanks :)

**Comment by ospfranco** [comment]
1. The library already parses urls for you with a more advanced regex
2. Right now there is no way to specify a timeout, but you can implement something on your own, https://stackoverflow.com/questions/46946380/fetch-api-request-timeout#46946573

**Comment by iMrDJAi** [comment]
Thx, but about the first point, It didn't really accept links without prefix protocol.
Should I to use fetch first to check if the server works? Isn't that make it slower?

**Comment by ospfranco** [comment]
ah, you are right, I might check if I can also include domains without protocol... chrome does it but I'm not sure about the edge cases

no, don't re implement the fetch call, but  `getLinkPreview` returns  a promise, you just have to check what returns first, the timeout or the getLinkPreview promise, so you can implement the same logic as in the snippets, but just replace the fetch call with the promise returned by `getLinkPreview`

**Comment by iMrDJAi** [comment]
By adding a `setTimeout` there then doing a check for the returned value?

**Comment by ospfranco** [comment]
The snippets are quite clear IMO, just pick w/e works for you

**Comment by iMrDJAi** [comment]
It works! Thx :)
By the way you can [remix](https://glitch.com/edit/#!/remix/embed-js the

**Comment by iMrDJAi** [comment]
Mistake*
It works! thanks :)
By the way you can [remix](https://glitch.com/edit/#!/remix/embed-js) the project and add it as a live demo if you want. :+1:
