### ISSUE TITLE
A problem with Cloudflare.

### ISSUE THREAD

**Issue by iMrDJAi** [ospfranco/link-preview-js#57]
**Describe the bug**
I was working on an embeds system, and because sometimes **link-preview-js** gives a valid image/favicon URL and sometimes not, and sometimes there is no URL at all, I tried to test it alone to check if its `mediaType` is an image.
The problem is that **link-preview-js** won't work with some Cloudflare protected domains, you will see on the title: `Access denied | domain used Cloudflare to restrict access`.
For example: [Discord](https://discordapp.com), the main page should work without any problem, but its [favicon URL](https://discordapp.com/assets/07dca80a102d4149e9736d4b162cff6f.ico) has this problem.

**To Reproduce**
1. Go to [this URL](https://embed-js.glitch.me/api?url=https%3A%2F%2Fdiscordapp.com%2Fassets%2F07dca80a102d4149e9736d4b162cff6f.ico).
2. See the result:

![image](https://user-images.githubusercontent.com/42304709/75040900-d3f6b600-54bb-11ea-9ace-392ba374ff9b.png)

**Expected behavior**
Something like this:

![image](https://user-images.githubusercontent.com/42304709/75040733-837f5880-54bb-11ea-88b0-945fabfab1c0.png).

**Screenshots**
The embed:

![image](https://user-images.githubusercontent.com/42304709/75041023-099b9f00-54bc-11ea-9911-890c06c2f5dd.png)

~~**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**~~
**Node:**
 - Node version: 10.x
 - Link-preview-js version: ^2.0.1

~~**Additional context**~~

**Comment by ospfranco** [comment]
I don't think there is much there is to do about this, I don't know how cloudfare does filtering for requests which they think are spam/bots/etc, maybe they filter via user-agent or some other logic, but doesn't sound like the library is doing anything wrong, this is just a third party preventing access to their assets.
