### ISSUE TITLE
Use parseTextResponse when no content type

### ISSUE THREAD

**Issue by yonathan06** [ospfranco/link-preview-js#58]
The current behavior is that an error is thrown if there is no content type header, or if it is not recognized.
Some websites does not send content type header (I have no idea why) or an unknown one for this library. For example [https://mjml.io/try-it-live](https://mjml.io/try-it-live)

Suggest a more tolerant approach and use `parseTextResponse` instead of throwing an error

**Comment by ospfranco** [comment]
Can you create a PR? I will merge it and publish a new version

**Comment by yonathan06** [comment]
https://github.com/ospfranco/link-preview-js/pull/59
