### ISSUE TITLE
2.0.2 is completely busted

### ISSUE THREAD

**Issue by guanzo** [ospfranco/link-preview-js#60]
Try any url, same error. `2.0.0` & `2.0.1` work fine

This PR is the likely culprit https://github.com/ospfranco/link-preview-js/pull/59

```
  err: Error: link-preview-js could not fetch link information TypeError: doc is not a function
      at C:\Users\Eric\workspace\suggestionbox\server\node_modules\link-preview-js\build\index.js:297:27
      at step (C:\Users\Eric\workspace\suggestionbox\server\node_modules\link-preview-js\build\index.js:33:23)
      at Object.next (C:\Users\Eric\workspace\suggestionbox\server\node_modules\link-preview-js\build\index.js:14:53)
      at fulfilled (C:\Users\Eric\workspace\suggestionbox\server\node_modules\link-preview-js\build\index.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by ospfranco** [comment]
ah damn, sorry about that, the tests where passing, I'll try to take a look later, is it any url that is causing the issue?

**Comment by guanzo** [comment]
any url yeah, including the ones at the top of the readme. I've tested in runkit & local machine.

Quick reproduction: https://npm.runkit.com/link-preview-js

This fails
```js
var {getLinkPreview} = require("link-preview-js@2.0.2")

getLinkPreview('https://www.youtube.com/watch?v=MejbOFk7H6c')
  .then(console.log);
```

change `2.0.2` to `2.0.1`, run again, it works.

**Comment by yonathan06** [comment]
I can see that `doc` is an function we from cheerio, returned after calling `cheerio.load()`
It is very weird, I added a new test to test this link you provided and it looks ok, not sure what change broke your code.
will have a deeper look
I think we need to replace `cheerio-without-node-native` in a more stable library, it is not updated for a long time.
@ospfranco  your thought?
@guanzo you can see the test I added to my forked repo https://github.com/yonathan06/link-preview-js

**Comment by ospfranco** [comment]
I was already in the process of removing cheerio without node native, but the options are limited, I was close using rn-html-parser, but I found a bug that returns too many nodes, in any case you can check the work I already did on the migrate to rn html parser branch:

**Comment by yonathan06** [comment]
@ospfranco it seems you published a new version to NPM without updating the master branch 
I see you added `import { ResponseModel } from './Response.model';` to the code (after installing `v2.0.2`), but I can't see that code in your repo

**Comment by ospfranco** [comment]
aha, could have been my mistake, let me try to publish a new version then, see if that works, I will also add running the tests to my publish script

**Comment by ospfranco** [comment]
2.0.4 is published, would you mind giving it try?

**Comment by yonathan06** [comment]
@ospfranco works for me!

**Comment by guanzo** [comment]
works for me, thx for the quick fix!

**Comment by ospfranco** [comment]
Cheers!
