### ISSUE TITLE
support meta name="" as a possible alternative to meta property="" for title, siteName, mediaType, images, videos

### ISSUE THREAD

**Issue by megantaylor** [ospfranco/link-preview-js#68]
the `name` attribute on a meta tag is equally valid and arguably more widely used. it should be supported as an alternative to the `property` attribute.

this is being done in a couple of places already (description checks for the name attribute first, then looks for the property attribute, for example) and could easily be expanded for the other properties.

i'd be happy to work on a PR for this, if its an acceptable idea.

**Comment by ospfranco** [comment]
Please do submit a PR
