### ISSUE TITLE
[Bug] Fails to return correct info on youtube link on a react-native environment

### ISSUE THREAD

**Issue by ospfranco** [ospfranco/link-preview-js#78]
**Describe the bug**
When using youtube link on react-native, youtube somehow redirects into the home page of the mobile version, effectively loosing all information relevant to the user

**To Reproduce**
1. Use a youtube link with link-preview-js while on a react-native env (emulator reproduces the issue)
2. The returned response will not contain the video information

**Expected behavior**
The returned object contains the video link and correct preview

**Additional context**
I don't think the problem lies within this library but rather, youtube taking a look into the user-agent and then redirecting the request into their mobile site which then returns the home page and not the right video link... which is all very stupid and convoluted but we can thank google for taking over the web

**Comment by ospfranco** [comment]
since this is not a problem with (at least I don't think it is), there is not much I plan to do about it, if someone wants to take a look into redirections and figure out why google is being stupid, feel free to take a look.

In the mean time I would recommend you move the link fetching to your back-end if this is a huge problem for you.

**Comment by mhui** [comment]
I noticed the example in the readme solves this problem. Setting the googlebot user-agent, at least on simulator

**Comment by ospfranco** [comment]
alright, if that solves then it really is a youtube redirection problem, closing this
