### ISSUE TITLE
Get youtube channel name - react native

### ISSUE THREAD

**Issue by Abhishek-Sankey** [ospfranco/link-preview-js#81]
Hi,
I was using `react-native-link-preview` before. I've one use case where I want the name of the youtube channel. So, i forked the lib and got the channel id using the below line...
`channel_id = doc('button[class="yt-uix-button yt-uix-button-size-default yt-uix-button-subscribe-branded yt-uix-button-has-icon no-icon-markup yt-uix-subscription-button yt-can-buffer yt-uix-servicelink vve-check"]').attr('data-channel-external-id');`

But after the library update, there's some issue with the channel id...

Can anyone plz help?
Thanks!

**Comment by ospfranco** [comment]
https://github.com/ospfranco/link-preview-js/issues/78

You can try to change the user-agent, but this is not a problem with the library itself

**Comment by Abhishek-Sankey** [comment]
@ospfranco i'm getting the video details(title, image, desc...) but I also want the channel name. Is there any way so that, I can get the channel name?

**Comment by ospfranco** [comment]
No idea, sorry
