### ISSUE TITLE
FaceBookPreview

### ISSUE THREAD

**Issue by TamilB** [ospfranco/link-preview-js#84]
Hi i am using Linkpreview Npm in that Doesn' show facebook Details correctly

**Comment by ospfranco** [comment]
Please create a reproducible example, with the link & expected output

**Comment by ospfranco** [comment]
I'm sorry, I actually dislike this issue, I'm not your slave, if you want to contribute meaningfully to the project put a little effort, otherwise you can pay me to add support for the features you need
