### ISSUE TITLE
get issue with YouTube link

### ISSUE THREAD

**Issue by Amazing1974** [ospfranco/link-preview-js#94]
I'm really happy to use this library. It works well with other links but not working with YouTube link.

getLinkPreview(youtube_url, {
            imagesPropertyType: "og",
            headers: {
                "user-agent": "googleblot",
                "Accept-Language": "en"
            }
        })

{
  "contentType": "text/html",
  "description": undefined,
  "favicons": Array [
    "https://www.google.com/favicon.ico",
  ],
  "images": Array [],
  "mediaType": "website",
  "siteName": undefined,
  "title": "Before you continue to YouTube",
  "url": "https://consent.youtube.com/ml?continue=https://www.youtube.com/watch?v%3Djbr928D9C0g&gl=GB&hl=en&pc=yt&uxe=23983172&src=1",
  "videos": Array [],
}

I'm always getting this response.
please help me.

**Comment by ospfranco** [comment]
you have a typo `googleblot` and as stated in the README, the library is fine
