### ISSUE TITLE
CORS policy blocks my requests

### ISSUE THREAD

**Issue by kritonpc** [ospfranco/link-preview-js#98]
**Describe the bug**
I get the error "Access to XMLHttpRequest at 'https://---------------' from origin 'http://-------------' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

I tried setting user agent but i get "Refused to set unsafe header "user-agent"". 
What can I do to fix this? I checked the readme as indicated in another CORS issue, but there is no hint of a solution there exept the user agent, that doesn't work.

**To Reproduce**
```this.loaded = false
        getLinkPreview(this.link, {
            headers: {
                // "user-agent": "googlebot",
                // "Accept-Language": "en-US", 
            }
        }).then((data) => this.linkData = data).finally(() => this.loaded=true);
```

**Desktop:**
 - OS: Win 10
 - Browser Chrome
 - Version 91

**Comment by ospfranco** [comment]
Read the README
